### ISSUE TITLE
Rename repository to "utilities" instead of "templates"?

### ISSUE THREAD

**Issue by naga-karthik** [ivadomed/utilities#9]
As mentioned in the title, this repository is evolving towards a collection of utility files for dataset conversion or training scripts or models, etc. Hence, I was thinking of renaming it to "utilities". What are your thoughts, @jcohenadad ?

**Comment by naga-karthik** [comment]
Renaming complete!

**Comment by valosekj** [comment]
Recently, @naga-karthik proposed a script for running the nnUNet inference (see [this PR](https://github.com/ivadomed/model_seg_sci/pull/40)). The script is currently located under the [ivadomed/model_seg_sci](https://github.com/ivadomed/model_seg_sci) repository. But since the script is universal, it could be moved to this repo. But then, the repo should probably be renamed back `utilities` (instead of the current `data-conversion`).

**Comment by naga-karthik** [comment]
I totally agree! The purpose of this repository was to indeed share a skeleton-structure of the utility scripts that the students could use it as it is or adapt it for their projects.

**Comment by valosekj** [comment]
Okay, thanks all for your feedback. Repo renamed back to `utilities`.
